### ISSUE TITLE
Exceptions raised within datagram_received difficult to use

### ISSUE THREAD

**Issue by gclinch** [hh-h/aiosnmp#12]
In production we run asyncio with a custom loop exception handler (https://docs.python.org/3/library/asyncio-eventloop.html#error-handling-api) that causes the process to completely abort for reliability when an unhandled exception occurs.

When an undecodable message is received (we have an item of equipment that sometimes cannot correctly format an Object Identifier(!)), an exception (eg "ASN1 syntax error") is raised from asn1 and never handled - thus the loop exception handler will be called.

Here's the traceback we log:

```
ERROR    Unhandled exception in loop - aborting
ERROR    Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 962, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.7/dist-packages/aiosnmp/protocols.py", line 95, in datagram_received
    message = SnmpResponse.decode(data)
  File "/usr/local/lib/python3.7/dist-packages/aiosnmp/message.py", line 178, in decode
    _, value = decoder.read()
  File "/usr/local/lib/python3.7/dist-packages/aiosnmp/asn1.py", line 380, in read
    value = self._read_value(nr, length)
  File "/usr/local/lib/python3.7/dist-packages/aiosnmp/asn1.py", line 473, in _read_value
    return self._decode_object_identifier(bytes_data)
  File "/usr/local/lib/python3.7/dist-packages/aiosnmp/asn1.py", line 561, in _decode_object_identifier
    raise Error("ASN1 syntax error")
aiosnmp.asn1.Error: ASN1 syntax error
```

Because this is corrupt data from a remote system, I think it should not cause an exception to be raised all the way to the loop, instead the data should be dropped, perhaps logging a message.

The default asyncio loop exception handler will log the exception details, drop the task and continue on.

Would you consider alterations to SnmpTrapProtocol.datagram_received & SnmpProtocol.datagram_received to capture exceptions raised by SnmpMessage.decode and simply log a message much like the default asyncio loop exception handler does?

**Comment by hh-h** [comment]
Hi. I'm not sure that a good idea just to drop such messages. This is an exception and should be raised somehow, perhaps it should be changed not to raise from asn parser. What the behavior of other frameworks (pysnmp, netsnmp, snmpget) in your case?

**Comment by gclinch** [comment]
Looking at the specific reproducible issue I have, which is receiving a response of (06, 00) - i.e. a zero-length OBJECT-IDENTIFIER:

pysnmp's hlapi.asyncio interface drops the response silently (although with 'msgproc' debugging enabled, the message "pysnmp: receiveMessage: Empty substrate" is sent to stderr), and so eventually a timeout exception is set.  But an exception never leaks all the way to the loop.

net-snmp processes the response (asn1.c includes a note to "Handle invalid object identifier encodings of the form 06 00 robustly") - it believes the response means the OID '0'.

wireshark also understands the record as meaning OID '0' but covers it with a warning of "Wrong value length: 0 expecting: 1 <= len <= 16777215".

Thinking more generally though, for connection-oriented protocols I would expect there to be a single future per connected socket, so that any exception during message reception would cause the exception to be set on the related future, and thus the calling code can take action.  But because the future here is keyed on (host, port, message.data.request_id), and message.data.request_id is not available in the case that SnmpResponse.decode fails, I don't see it is currently possible to expose the exception in that way.

Currently calling code cannot do anything other than wait for the timeout that fires (which is similar to pysnmp), because it doesn't receive the exception unless it has also set a custom loop exception handler - and that's so far from the context of the originating SNMP request that the exception is almost meaningless in terms of recovery action to take.

**Comment by hh-h** [comment]
Thank you for your investigation! Please, take a look at the attached PR. I'm not sure about the log level, thoughts? (I hope I got you right, haha)

**Comment by gclinch** [comment]
Yes, that's perfect, thanks!  As to the log level, I would probably have chosen warning rather than error (because the 'error' is the timeout from not receiving a valid reply that comes a bit later on), but I suspect three different people would have three different angles on that.  Because there's a named logger developers can always alter its effective level depending on whether they want to see the message or not, so I'd not worry too much about the actual level chosen as long as it's consistent with other potential uses of the aiosnmp logger in future.

**Comment by hh-h** [comment]
Actually, warning makes more sense 👍
