### ISSUE TITLE
Exception appear AssertionError, no message, i don't know why to cause this error

### ISSUE THREAD

**Issue by daiyongjian** [hh-h/aiosnmp#19]
async def walk_snmp(self, ip, oid):
        """
        request snmp
        :param ip:
        :param oid:
        :return:
        """
        items = []
        try:
            async with aiosnmp.Snmp(
                    host=ip,
                    community='xxx',
                    version=aiosnmp.message.SnmpVersion.v2c,
                    timeout=self.snmp_timeout,
                    retries=self.snmp_retry
            ) as snmp:
                items = await snmp.bulk_walk(oid)
        except (SnmpTimeoutError, TimeoutError):
            self.redis_cli.hset('timeout', f'{ip}-{oid}', 'timeout')
            return
        except Exception as err:
            self.redis_cli.hset('error', f'{ip}-{oid}', str(err))
            return

**Comment by hh-h** [comment]
Hi, could you paste the output of this snippet? What oid do you use?

**Comment by daiyongjian** [comment]
<class 'AssertionError'>
1.3.6.1.2.1.2.2.1.9

<class 'AssertionError'>
1.3.6.1.2.1.31.1.1.1.10

<class 'AssertionError'>
1.3.6.1.2.1.2.2.1.13

<class 'AssertionError'>
1.3.6.1.2.1.31.1.1.1.13

<class 'AssertionError'>
1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7


I use this snippet
```
        try:
            async with aiosnmp.Snmp(
                    host=ip,
                    community='xxx',
                    version=aiosnmp.message.SnmpVersion.v2c,
                    timeout=self.snmp_timeout,
                    retries=self.snmp_retry
            ) as snmp:
                items = await snmp.bulk_walk(oid)
        except (SnmpTimeoutError, TimeoutError):
            self.redis_cli.hset('timeout', f'{ip}-{oid}', 'timeout')
            return
        except Exception as err:
            print(oid)
            print(err)
            print(type(err))
            self.redis_cli.hset('error', f'{ip}-{oid}', str(err))
            return
```

**Comment by daiyongjian** [comment]
I set asyncio timeout is 20s, retry 3, snmp timeout 4, so maybe retry timeout don't have Exception class?i don't know

**Comment by hh-h** [comment]
Do you use ipv4 or ipv6 address?  
Try to run your script with `-O` flag (`python -O script.py`)  (O, not zero)

**Comment by daiyongjian** [comment]
I use ipv4

**Comment by hh-h** [comment]
I added more questions and steps above, please check.

**Comment by hh-h** [comment]
Could you describe why you've closed the issue? It could be a potential bug actually...

**Comment by daiyongjian** [comment]
<class 'TypeError'>
'NoneType' object is not subscriptable
<class 'TypeError'>
'NoneType' object is not subscriptable
<class 'TypeError'>
'NoneType' object is not subscriptable
<class 'TypeError'>
'NoneType' object is not subscriptable
<class 'TypeError'>
'NoneType' object is not subscriptable

**Comment by daiyongjian** [comment]
Debian 10 Python3

**Comment by daiyongjian** [comment]
remove arsync  not effect

**Comment by daiyongjian** [comment]
brand is h3c,loop number is 3600

**Comment by hh-h** [comment]
just run this code
```
async def walk_snmp(self, ip, oid):
    """
    request snmp
    :param ip:
    :param oid:
    :return:
    """
    items = []
    async with aiosnmp.Snmp(
                host=ip,
                community='xxx',
                version=aiosnmp.message.SnmpVersion.v2c,
                timeout=self.snmp_timeout,
                retries=self.snmp_retry
    ) as snmp:
        items = await snmp.bulk_walk(oid)
```

without any try/except blocks and paste the output here (`python -O script.py`)

**Comment by fthyssen** [comment]
I'm a bit late to notice this issue, but I hope this can help.

I can see many `assert`s have been replaced, nice!

I did find an assert here
https://github.com/hh-h/aiosnmp/blob/037bcc3ff2cd8ec2363dbf29f4195d191c2bf0de/aiosnmp/snmp.py#L59-L67

As per [get_extra_info](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info), `"peername"` could return `None` on error.
If that's not part of the `default` scenario, there should probably be an explicit fallback to `(self.host, self.port)` here (and `default=(...)` can then just be removed):
https://github.com/hh-h/aiosnmp/blob/037bcc3ff2cd8ec2363dbf29f4195d191c2bf0de/aiosnmp/connection.py#L52

A quick glance at cpython code seems to confirm that scenario is possible.

(All) other `assert`s are in [asn1.py](https://github.com/hh-h/aiosnmp/blob/037bcc3ff2cd8ec2363dbf29f4195d191c2bf0de/aiosnmp/asn1.py).

It would indeed be best to see the error in action, or at least reproduced and hopefully fixed.

**Comment by hh-h** [comment]
I can't fix the issue, since you haven't provided output from my previous comment.

**Comment by hh-h** [comment]
author is missing
