### ISSUE TITLE
Please allow close SNMPtrap

### ISSUE THREAD

**Issue by smathieson** [hh-h/aiosnmp#21]
The SNMP trap class does not allow closing of the endpoint.

run callable can be changed to return the transport, which can be closed:

    async def run(self) -> None:
        loop = asyncio.get_event_loop()

        transport, _ = await loop.create_datagram_endpoint(
            lambda: SnmpTrapProtocol(self.communities, self.handler),
            local_addr=(self.host, self.port),
        )
        return transport

Thanks for the library!

**Comment by hh-h** [comment]
Suddenly I realized that I haven't had time to test traps at all, will try to fix that on weekend :)
