### ISSUE TITLE
 bulk_walk does not accept a list of oids

### ISSUE THREAD

**Issue by MIKNOTAURO** [hh-h/aiosnmp#23]
Hi, 
As far as I understand, bulk_walk should accept a list of oids to optimize network calls, but I'm not sure... My guess is based on easysnmp (I can't use this repo, because is not async).

Could you help to clarify?

**Comment by hh-h** [comment]
Hi,
`snmpbulkwalk` (or other bulk variants) doesn't support multiple oids, the quote from reference https://linux.die.net/man/1/snmpbulkwalk

> snmpbulkwalk [APPLICATION OPTIONS] [COMMON OPTIONS] [OID]

`easysnmp` just iterates over all varbinds and calls `snmpbulkwalk`, see https://github.com/fgimian/easysnmp/blob/master/easysnmp/interface.c#L3545

`aiosnmp` does it in a "parallel" way and it is much faster, just use `asyncio.gather`. I can provide an example if you need one.

Cheers!

**Comment by MIKNOTAURO** [comment]
Thanks for your fast answer,
And if you can help me with the example, that would be really appreciated ;)

**Comment by hh-h** [comment]
here you go
```
import asyncio

import aiosnmp


async def main():
    async with aiosnmp.Snmp(host="127.0.0.1", community="public") as snmp:
        coros = [
            snmp.bulk_walk(".1.3.6.1.2.1.1"),
            snmp.bulk_walk(".1.3.6.1.2.1.2.2.1.2"),
            # add more here in the same manner
        ]

        sys_descr, if_table = await asyncio.gather(*coros)
        print("sys_descr")
        for vb in sys_descr:
            print(vb.oid, vb.value)

        print("if_table")
        for vb in if_table:
            print(vb.oid, vb.value)


asyncio.run(main())
```

**Comment by MIKNOTAURO** [comment]
Thank you so much!... Now, it works ;)
